### ISSUE TITLE
Track messages posted in channels

### ISSUE THREAD

**Issue by RaasAhsan** [forestbelton/naomi#32]
Add a feature to track messages posted by people in any channel naomi is in. This should be persisted to the sqlite db.

columns to track:
- message id
- message
- user
- user discriminator
- channel posted
- time posted
- etc

questions to answer:
- what indexes should we create on this table

Down the line, we can create new issues for creating commands that will consume this data.

**Comment by bramz** [comment]
https://github.com/forestbelton/naomi/pull/31/commits/03c09f438b14ad84c77367088bd0f833741682c3 

Ready to address any issues or changes we need to make
